apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: compose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: model-app
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      nodePort: 30004
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
